import Nconv from './nconv'

describe('romajiToHiragana', () => {
  test('基本', () => {
    expect(Nconv.romajiToHiragana('aiueo')).toBe('あいうえお')
    expect(Nconv.romajiToHiragana('kakikukeko')).toBe('かきくけこ')
    expect(Nconv.romajiToHiragana('sasisuseso')).toBe('さしすせそ')
    expect(Nconv.romajiToHiragana('tatituteto')).toBe('たちつてと')
    expect(Nconv.romajiToHiragana('naninuneno')).toBe('なにぬねの')
    expect(Nconv.romajiToHiragana('hahihuheho')).toBe('はひふへほ')
    expect(Nconv.romajiToHiragana('mamimumemo')).toBe('まみむめも')
    expect(Nconv.romajiToHiragana('yayuyeyo')).toBe('やゆいぇよ')
    expect(Nconv.romajiToHiragana('rarirurero')).toBe('らりるれろ')
    expect(Nconv.romajiToHiragana('wawo')).toBe('わを')
    expect(Nconv.romajiToHiragana('nn')).toBe('ん')
    expect(Nconv.romajiToHiragana('-')).toBe('ー')

    expect(Nconv.romajiToHiragana('gagigugego')).toBe('がぎぐげご')
    expect(Nconv.romajiToHiragana('zazizuzezo')).toBe('ざじずぜぞ')
    expect(Nconv.romajiToHiragana('dadidudedo')).toBe('だぢづでど')
    expect(Nconv.romajiToHiragana('babibubebo')).toBe('ばびぶべぼ')
    expect(Nconv.romajiToHiragana('papipupepo')).toBe('ぱぴぷぺぽ')

    expect(Nconv.romajiToHiragana('kyakyikyukyekyo')).toBe('きゃきぃきゅきぇきょ')
    expect(Nconv.romajiToHiragana('gyagyigyugyegyo')).toBe('ぎゃぎぃぎゅぎぇぎょ')
    expect(Nconv.romajiToHiragana('syasyisyusyesyo')).toBe('しゃしぃしゅしぇしょ')
    expect(Nconv.romajiToHiragana('zyazyizyuzyezyo')).toBe('じゃじぃじゅじぇじょ')
    expect(Nconv.romajiToHiragana('jyajyijyujyejyo')).toBe('じゃじぃじゅじぇじょ')
    expect(Nconv.romajiToHiragana('tyatyityutyetyo')).toBe('ちゃちぃちゅちぇちょ')
    expect(Nconv.romajiToHiragana('cyacyicyucyecyo')).toBe('ちゃちぃちゅちぇちょ')
    expect(Nconv.romajiToHiragana('dyadyidyudyedyo')).toBe('ぢゃぢぃぢゅぢぇぢょ')
    expect(Nconv.romajiToHiragana('hyahyihyuhyehyo')).toBe('ひゃひぃひゅひぇひょ')
    expect(Nconv.romajiToHiragana('byabyibyubyebyo')).toBe('びゃびぃびゅびぇびょ')

    expect(Nconv.romajiToHiragana('fafifufefo')).toBe('ふぁふぃふふぇふぉ')
    expect(Nconv.romajiToHiragana('jajijujejo')).toBe('じゃじじゅじぇじょ')
    expect(Nconv.romajiToHiragana('qaqiquqeqo')).toBe('くぁくぃくくぇくぉ')
    expect(Nconv.romajiToHiragana('vavivuvevo')).toBe('ゔぁゔぃゔゔぇゔぉ')

    expect(Nconv.romajiToHiragana('shi')).toBe('し')
    expect(Nconv.romajiToHiragana('chi')).toBe('ち')
    expect(Nconv.romajiToHiragana('tsu')).toBe('つ')

    expect(Nconv.romajiToHiragana('xaxixuxexo')).toBe('ぁぃぅぇぉ')
    expect(Nconv.romajiToHiragana('lalilulelo')).toBe('ぁぃぅぇぉ')
    expect(Nconv.romajiToHiragana('xyaxyuxyo')).toBe('ゃゅょ')
    expect(Nconv.romajiToHiragana('lyalyulyo')).toBe('ゃゅょ')
    expect(Nconv.romajiToHiragana('xtu')).toBe('っ')
    expect(Nconv.romajiToHiragana('ltu')).toBe('っ')
    expect(Nconv.romajiToHiragana('xtsu')).toBe('っ')
    expect(Nconv.romajiToHiragana('ltsu')).toBe('っ')

    expect(Nconv.romajiToHiragana('knkn')).toBe('kんkん')
  })

  test('重ね子音字', () => {
    expect(Nconv.romajiToHiragana('kkakkikkukkekko')).toBe('っかっきっくっけっこ')
    expect(Nconv.romajiToHiragana('ssassissussesso')).toBe('っさっしっすっせっそ')
    expect(Nconv.romajiToHiragana('ttattittuttetto')).toBe('ったっちっつってっと')
    expect(Nconv.romajiToHiragana('nnanninnunnenno')).toBe('んあんいんうんえんお')
    expect(Nconv.romajiToHiragana('hhahhihhuhhehho')).toBe('っはっひっふっへっほ')
    expect(Nconv.romajiToHiragana('mmammimmummemmo')).toBe('っまっみっむっめっも')
    expect(Nconv.romajiToHiragana('yyayyuyyeyyo')).toBe('っやっゆっいぇっよ')
    expect(Nconv.romajiToHiragana('rrarrirrurrerro')).toBe('っらっりっるっれっろ')
    expect(Nconv.romajiToHiragana('wwawwo')).toBe('っわっを')

    expect(Nconv.romajiToHiragana('ggaggigguggeggo')).toBe('っがっぎっぐっげっご')
    expect(Nconv.romajiToHiragana('zzazzizzuzzezzo')).toBe('っざっじっずっぜっぞ')
    expect(Nconv.romajiToHiragana('ddaddidduddeddo')).toBe('っだっぢっづっでっど')
    expect(Nconv.romajiToHiragana('bbabbibbubbebbo')).toBe('っばっびっぶっべっぼ')
    expect(Nconv.romajiToHiragana('ppappippuppeppo')).toBe('っぱっぴっぷっぺっぽ')

    expect(Nconv.romajiToHiragana('kkyakkyikkyukkyekkyo')).toBe('っきゃっきぃっきゅっきぇっきょ')
    expect(Nconv.romajiToHiragana('ggyaggyiggyuggyeggyo')).toBe('っぎゃっぎぃっぎゅっぎぇっぎょ')
    expect(Nconv.romajiToHiragana('ssyassyissyussyessyo')).toBe('っしゃっしぃっしゅっしぇっしょ')
    expect(Nconv.romajiToHiragana('zzyazzyizzyuzzyezzyo')).toBe('っじゃっじぃっじゅっじぇっじょ')
    expect(Nconv.romajiToHiragana('jjyajjyijjyujjyejjyo')).toBe('っじゃっじぃっじゅっじぇっじょ')
    expect(Nconv.romajiToHiragana('ttyattyittyuttyettyo')).toBe('っちゃっちぃっちゅっちぇっちょ')
    expect(Nconv.romajiToHiragana('ccyaccyiccyuccyeccyo')).toBe('っちゃっちぃっちゅっちぇっちょ')
    expect(Nconv.romajiToHiragana('ddyaddyiddyuddyeddyo')).toBe('っぢゃっぢぃっぢゅっぢぇっぢょ')
    expect(Nconv.romajiToHiragana('hhyahhyihhyuhhyehhyo')).toBe('っひゃっひぃっひゅっひぇっひょ')
    expect(Nconv.romajiToHiragana('bbyabbyibbyubbyebbyo')).toBe('っびゃっびぃっびゅっびぇっびょ')

    expect(Nconv.romajiToHiragana('ffaffiffuffeffo')).toBe('っふぁっふぃっふっふぇっふぉ')
    expect(Nconv.romajiToHiragana('jjajjijjujjejjo')).toBe('っじゃっじっじゅっじぇっじょ')
    expect(Nconv.romajiToHiragana('qqaqqiqquqqeqqo')).toBe('っくぁっくぃっくっくぇっくぉ')
    expect(Nconv.romajiToHiragana('vvavvivvuvvevvo')).toBe('っゔぁっゔぃっゔっゔぇっゔぉ')

    expect(Nconv.romajiToHiragana('sshi')).toBe('っし')
    expect(Nconv.romajiToHiragana('cchi')).toBe('っち')
    expect(Nconv.romajiToHiragana('ttsu')).toBe('っつ')

    expect(Nconv.romajiToHiragana('xxaxxixxuxxexxo')).toBe('っぁっぃっぅっぇっぉ')
    expect(Nconv.romajiToHiragana('llallillullello')).toBe('っぁっぃっぅっぇっぉ')
    expect(Nconv.romajiToHiragana('xxyaxxyuxxyo')).toBe('っゃっゅっょ')
    expect(Nconv.romajiToHiragana('llyallyullyo')).toBe('っゃっゅっょ')
    expect(Nconv.romajiToHiragana('xxtu')).toBe('っっ')
    expect(Nconv.romajiToHiragana('lltu')).toBe('っっ')
    expect(Nconv.romajiToHiragana('xxtsu')).toBe('っっ')
    expect(Nconv.romajiToHiragana('lltsu')).toBe('っっ')

    expect(Nconv.romajiToHiragana('kkkkka')).toBe('っっっっか')
  })

})

describe('romajiToZenkakuKatakana', () => {
  test('基本', () => {
    expect(Nconv.romajiToZenkakuKatakana('aiueo')).toBe('アイウエオ')
    expect(Nconv.romajiToZenkakuKatakana('kakikukeko')).toBe('カキクケコ')
    expect(Nconv.romajiToZenkakuKatakana('sasisuseso')).toBe('サシスセソ')
    expect(Nconv.romajiToZenkakuKatakana('tatituteto')).toBe('タチツテト')
    expect(Nconv.romajiToZenkakuKatakana('naninuneno')).toBe('ナニヌネノ')
    expect(Nconv.romajiToZenkakuKatakana('hahihuheho')).toBe('ハヒフヘホ')
    expect(Nconv.romajiToZenkakuKatakana('mamimumemo')).toBe('マミムメモ')
    expect(Nconv.romajiToZenkakuKatakana('yayuyeyo')).toBe('ヤユイェヨ')
    expect(Nconv.romajiToZenkakuKatakana('rarirurero')).toBe('ラリルレロ')
    expect(Nconv.romajiToZenkakuKatakana('wawo')).toBe('ワヲ')
    expect(Nconv.romajiToZenkakuKatakana('nn')).toBe('ン')
    expect(Nconv.romajiToZenkakuKatakana('-')).toBe('ー')

    expect(Nconv.romajiToZenkakuKatakana('gagigugego')).toBe('ガギグゲゴ')
    expect(Nconv.romajiToZenkakuKatakana('zazizuzezo')).toBe('ザジズゼゾ')
    expect(Nconv.romajiToZenkakuKatakana('dadidudedo')).toBe('ダヂヅデド')
    expect(Nconv.romajiToZenkakuKatakana('babibubebo')).toBe('バビブベボ')
    expect(Nconv.romajiToZenkakuKatakana('papipupepo')).toBe('パピプペポ')

    expect(Nconv.romajiToZenkakuKatakana('kyakyikyukyekyo')).toBe('キャキィキュキェキョ')
    expect(Nconv.romajiToZenkakuKatakana('gyagyigyugyegyo')).toBe('ギャギィギュギェギョ')
    expect(Nconv.romajiToZenkakuKatakana('syasyisyusyesyo')).toBe('シャシィシュシェショ')
    expect(Nconv.romajiToZenkakuKatakana('zyazyizyuzyezyo')).toBe('ジャジィジュジェジョ')
    expect(Nconv.romajiToZenkakuKatakana('jyajyijyujyejyo')).toBe('ジャジィジュジェジョ')
    expect(Nconv.romajiToZenkakuKatakana('tyatyityutyetyo')).toBe('チャチィチュチェチョ')
    expect(Nconv.romajiToZenkakuKatakana('cyacyicyucyecyo')).toBe('チャチィチュチェチョ')
    expect(Nconv.romajiToZenkakuKatakana('dyadyidyudyedyo')).toBe('ヂャヂィヂュヂェヂョ')
    expect(Nconv.romajiToZenkakuKatakana('hyahyihyuhyehyo')).toBe('ヒャヒィヒュヒェヒョ')
    expect(Nconv.romajiToZenkakuKatakana('byabyibyubyebyo')).toBe('ビャビィビュビェビョ')

    expect(Nconv.romajiToZenkakuKatakana('fafifufefo')).toBe('ファフィフフェフォ')
    expect(Nconv.romajiToZenkakuKatakana('jajijujejo')).toBe('ジャジジュジェジョ')
    expect(Nconv.romajiToZenkakuKatakana('qaqiquqeqo')).toBe('クァクィククェクォ')
    expect(Nconv.romajiToZenkakuKatakana('vavivuvevo')).toBe('ヴァヴィヴヴェヴォ')

    expect(Nconv.romajiToZenkakuKatakana('shi')).toBe('シ')
    expect(Nconv.romajiToZenkakuKatakana('chi')).toBe('チ')
    expect(Nconv.romajiToZenkakuKatakana('tsu')).toBe('ツ')

    expect(Nconv.romajiToZenkakuKatakana('xaxixuxexo')).toBe('ァィゥェォ')
    expect(Nconv.romajiToZenkakuKatakana('lalilulelo')).toBe('ァィゥェォ')
    expect(Nconv.romajiToZenkakuKatakana('xyaxyuxyo')).toBe('ャュョ')
    expect(Nconv.romajiToZenkakuKatakana('lyalyulyo')).toBe('ャュョ')
    expect(Nconv.romajiToZenkakuKatakana('xtu')).toBe('ッ')
    expect(Nconv.romajiToZenkakuKatakana('ltu')).toBe('ッ')
    expect(Nconv.romajiToZenkakuKatakana('xtsu')).toBe('ッ')
    expect(Nconv.romajiToZenkakuKatakana('ltsu')).toBe('ッ')

    expect(Nconv.romajiToZenkakuKatakana('knkn')).toBe('kンkン')
  })

  test('重ね子音字', () => {
    expect(Nconv.romajiToZenkakuKatakana('kkakkikkukkekko')).toBe('ッカッキックッケッコ')
    expect(Nconv.romajiToZenkakuKatakana('ssassissussesso')).toBe('ッサッシッスッセッソ')
    expect(Nconv.romajiToZenkakuKatakana('ttattittuttetto')).toBe('ッタッチッツッテット')
    expect(Nconv.romajiToZenkakuKatakana('nnanninnunnenno')).toBe('ンアンインウンエンオ')
    expect(Nconv.romajiToZenkakuKatakana('hhahhihhuhhehho')).toBe('ッハッヒッフッヘッホ')
    expect(Nconv.romajiToZenkakuKatakana('mmammimmummemmo')).toBe('ッマッミッムッメッモ')
    expect(Nconv.romajiToZenkakuKatakana('yyayyuyyeyyo')).toBe('ッヤッユッイェッヨ')
    expect(Nconv.romajiToZenkakuKatakana('rrarrirrurrerro')).toBe('ッラッリッルッレッロ')
    expect(Nconv.romajiToZenkakuKatakana('wwawwo')).toBe('ッワッヲ')

    expect(Nconv.romajiToZenkakuKatakana('ggaggigguggeggo')).toBe('ッガッギッグッゲッゴ')
    expect(Nconv.romajiToZenkakuKatakana('zzazzizzuzzezzo')).toBe('ッザッジッズッゼッゾ')
    expect(Nconv.romajiToZenkakuKatakana('ddaddidduddeddo')).toBe('ッダッヂッヅッデッド')
    expect(Nconv.romajiToZenkakuKatakana('bbabbibbubbebbo')).toBe('ッバッビッブッベッボ')
    expect(Nconv.romajiToZenkakuKatakana('ppappippuppeppo')).toBe('ッパッピップッペッポ')

    expect(Nconv.romajiToZenkakuKatakana('kkyakkyikkyukkyekkyo')).toBe('ッキャッキィッキュッキェッキョ')
    expect(Nconv.romajiToZenkakuKatakana('ggyaggyiggyuggyeggyo')).toBe('ッギャッギィッギュッギェッギョ')
    expect(Nconv.romajiToZenkakuKatakana('ssyassyissyussyessyo')).toBe('ッシャッシィッシュッシェッショ')
    expect(Nconv.romajiToZenkakuKatakana('zzyazzyizzyuzzyezzyo')).toBe('ッジャッジィッジュッジェッジョ')
    expect(Nconv.romajiToZenkakuKatakana('jjyajjyijjyujjyejjyo')).toBe('ッジャッジィッジュッジェッジョ')
    expect(Nconv.romajiToZenkakuKatakana('ttyattyittyuttyettyo')).toBe('ッチャッチィッチュッチェッチョ')
    expect(Nconv.romajiToZenkakuKatakana('ccyaccyiccyuccyeccyo')).toBe('ッチャッチィッチュッチェッチョ')
    expect(Nconv.romajiToZenkakuKatakana('ddyaddyiddyuddyeddyo')).toBe('ッヂャッヂィッヂュッヂェッヂョ')
    expect(Nconv.romajiToZenkakuKatakana('hhyahhyihhyuhhyehhyo')).toBe('ッヒャッヒィッヒュッヒェッヒョ')
    expect(Nconv.romajiToZenkakuKatakana('bbyabbyibbyubbyebbyo')).toBe('ッビャッビィッビュッビェッビョ')

    expect(Nconv.romajiToZenkakuKatakana('ffaffiffuffeffo')).toBe('ッファッフィッフッフェッフォ')
    expect(Nconv.romajiToZenkakuKatakana('jjajjijjujjejjo')).toBe('ッジャッジッジュッジェッジョ')
    expect(Nconv.romajiToZenkakuKatakana('qqaqqiqquqqeqqo')).toBe('ックァックィックックェックォ')
    expect(Nconv.romajiToZenkakuKatakana('vvavvivvuvvevvo')).toBe('ッヴァッヴィッヴッヴェッヴォ')

    expect(Nconv.romajiToZenkakuKatakana('sshi')).toBe('ッシ')
    expect(Nconv.romajiToZenkakuKatakana('cchi')).toBe('ッチ')
    expect(Nconv.romajiToZenkakuKatakana('ttsu')).toBe('ッツ')

    expect(Nconv.romajiToZenkakuKatakana('xxaxxixxuxxexxo')).toBe('ッァッィッゥッェッォ')
    expect(Nconv.romajiToZenkakuKatakana('llallillullello')).toBe('ッァッィッゥッェッォ')
    expect(Nconv.romajiToZenkakuKatakana('xxyaxxyuxxyo')).toBe('ッャッュッョ')
    expect(Nconv.romajiToZenkakuKatakana('llyallyullyo')).toBe('ッャッュッョ')
    expect(Nconv.romajiToZenkakuKatakana('xxtu')).toBe('ッッ')
    expect(Nconv.romajiToZenkakuKatakana('lltu')).toBe('ッッ')
    expect(Nconv.romajiToZenkakuKatakana('xxtsu')).toBe('ッッ')
    expect(Nconv.romajiToZenkakuKatakana('lltsu')).toBe('ッッ')

    expect(Nconv.romajiToZenkakuKatakana('kkkkka')).toBe('ッッッッカ')
  })

})

describe('romajiToHankakuKatakana', () => {
  test('基本', () => {
    expect(Nconv.romajiToHankakuKatakana('aiueo')).toBe('ｱｲｳｴｵ')
    expect(Nconv.romajiToHankakuKatakana('kakikukeko')).toBe('ｶｷｸｹｺ')
    expect(Nconv.romajiToHankakuKatakana('sasisuseso')).toBe('ｻｼｽｾｿ')
    expect(Nconv.romajiToHankakuKatakana('tatituteto')).toBe('ﾀﾁﾂﾃﾄ')
    expect(Nconv.romajiToHankakuKatakana('naninuneno')).toBe('ﾅﾆﾇﾈﾉ')
    expect(Nconv.romajiToHankakuKatakana('hahihuheho')).toBe('ﾊﾋﾌﾍﾎ')
    expect(Nconv.romajiToHankakuKatakana('mamimumemo')).toBe('ﾏﾐﾑﾒﾓ')
    expect(Nconv.romajiToHankakuKatakana('yayuyeyo')).toBe('ﾔﾕｲｪﾖ')
    expect(Nconv.romajiToHankakuKatakana('rarirurero')).toBe('ﾗﾘﾙﾚﾛ')
    expect(Nconv.romajiToHankakuKatakana('wawo')).toBe('ﾜｦ')
    expect(Nconv.romajiToHankakuKatakana('nn')).toBe('ﾝ')
    expect(Nconv.romajiToHankakuKatakana('-')).toBe('ｰ')

    expect(Nconv.romajiToHankakuKatakana('gagigugego')).toBe('ｶﾞｷﾞｸﾞｹﾞｺﾞ')
    expect(Nconv.romajiToHankakuKatakana('zazizuzezo')).toBe('ｻﾞｼﾞｽﾞｾﾞｿﾞ')
    expect(Nconv.romajiToHankakuKatakana('dadidudedo')).toBe('ﾀﾞﾁﾞﾂﾞﾃﾞﾄﾞ')
    expect(Nconv.romajiToHankakuKatakana('babibubebo')).toBe('ﾊﾞﾋﾞﾌﾞﾍﾞﾎﾞ')
    expect(Nconv.romajiToHankakuKatakana('papipupepo')).toBe('ﾊﾟﾋﾟﾌﾟﾍﾟﾎﾟ')

    expect(Nconv.romajiToHankakuKatakana('kyakyikyukyekyo')).toBe('ｷｬｷｨｷｭｷｪｷｮ')
    expect(Nconv.romajiToHankakuKatakana('gyagyigyugyegyo')).toBe('ｷﾞｬｷﾞｨｷﾞｭｷﾞｪｷﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('syasyisyusyesyo')).toBe('ｼｬｼｨｼｭｼｪｼｮ')
    expect(Nconv.romajiToHankakuKatakana('zyazyizyuzyezyo')).toBe('ｼﾞｬｼﾞｨｼﾞｭｼﾞｪｼﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('jyajyijyujyejyo')).toBe('ｼﾞｬｼﾞｨｼﾞｭｼﾞｪｼﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('tyatyityutyetyo')).toBe('ﾁｬﾁｨﾁｭﾁｪﾁｮ')
    expect(Nconv.romajiToHankakuKatakana('cyacyicyucyecyo')).toBe('ﾁｬﾁｨﾁｭﾁｪﾁｮ')
    expect(Nconv.romajiToHankakuKatakana('dyadyidyudyedyo')).toBe('ﾁﾞｬﾁﾞｨﾁﾞｭﾁﾞｪﾁﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('hyahyihyuhyehyo')).toBe('ﾋｬﾋｨﾋｭﾋｪﾋｮ')
    expect(Nconv.romajiToHankakuKatakana('byabyibyubyebyo')).toBe('ﾋﾞｬﾋﾞｨﾋﾞｭﾋﾞｪﾋﾞｮ')

    expect(Nconv.romajiToHankakuKatakana('fafifufefo')).toBe('ﾌｧﾌｨﾌﾌｪﾌｫ')
    expect(Nconv.romajiToHankakuKatakana('jajijujejo')).toBe('ｼﾞｬｼﾞｼﾞｭｼﾞｪｼﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('qaqiquqeqo')).toBe('ｸｧｸｨｸｸｪｸｫ')
    expect(Nconv.romajiToHankakuKatakana('vavivuvevo')).toBe('ｳﾞｧｳﾞｨｳﾞｳﾞｪｳﾞｫ')

    expect(Nconv.romajiToHankakuKatakana('shi')).toBe('ｼ')
    expect(Nconv.romajiToHankakuKatakana('chi')).toBe('ﾁ')
    expect(Nconv.romajiToHankakuKatakana('tsu')).toBe('ﾂ')

    expect(Nconv.romajiToHankakuKatakana('xaxixuxexo')).toBe('ｧｨｩｪｫ')
    expect(Nconv.romajiToHankakuKatakana('lalilulelo')).toBe('ｧｨｩｪｫ')
    expect(Nconv.romajiToHankakuKatakana('xyaxyuxyo')).toBe('ｬｭｮ')
    expect(Nconv.romajiToHankakuKatakana('lyalyulyo')).toBe('ｬｭｮ')
    expect(Nconv.romajiToHankakuKatakana('xtu')).toBe('ｯ')
    expect(Nconv.romajiToHankakuKatakana('ltu')).toBe('ｯ')
    expect(Nconv.romajiToHankakuKatakana('xtsu')).toBe('ｯ')
    expect(Nconv.romajiToHankakuKatakana('ltsu')).toBe('ｯ')

    expect(Nconv.romajiToHankakuKatakana('knkn')).toBe('kﾝkﾝ')
  })

  test('重ね子音字', () => {
    expect(Nconv.romajiToHankakuKatakana('kkakkikkukkekko')).toBe('ｯｶｯｷｯｸｯｹｯｺ')
    expect(Nconv.romajiToHankakuKatakana('ssassissussesso')).toBe('ｯｻｯｼｯｽｯｾｯｿ')
    expect(Nconv.romajiToHankakuKatakana('ttattittuttetto')).toBe('ｯﾀｯﾁｯﾂｯﾃｯﾄ')
    expect(Nconv.romajiToHankakuKatakana('nnanninnunnenno')).toBe('ﾝｱﾝｲﾝｳﾝｴﾝｵ')
    expect(Nconv.romajiToHankakuKatakana('hhahhihhuhhehho')).toBe('ｯﾊｯﾋｯﾌｯﾍｯﾎ')
    expect(Nconv.romajiToHankakuKatakana('mmammimmummemmo')).toBe('ｯﾏｯﾐｯﾑｯﾒｯﾓ')
    expect(Nconv.romajiToHankakuKatakana('yyayyuyyeyyo')).toBe('ｯﾔｯﾕｯｲｪｯﾖ')
    expect(Nconv.romajiToHankakuKatakana('rrarrirrurrerro')).toBe('ｯﾗｯﾘｯﾙｯﾚｯﾛ')
    expect(Nconv.romajiToHankakuKatakana('wwawwo')).toBe('ｯﾜｯｦ')

    expect(Nconv.romajiToHankakuKatakana('ggaggigguggeggo')).toBe('ｯｶﾞｯｷﾞｯｸﾞｯｹﾞｯｺﾞ')
    expect(Nconv.romajiToHankakuKatakana('zzazzizzuzzezzo')).toBe('ｯｻﾞｯｼﾞｯｽﾞｯｾﾞｯｿﾞ')
    expect(Nconv.romajiToHankakuKatakana('ddaddidduddeddo')).toBe('ｯﾀﾞｯﾁﾞｯﾂﾞｯﾃﾞｯﾄﾞ')
    expect(Nconv.romajiToHankakuKatakana('bbabbibbubbebbo')).toBe('ｯﾊﾞｯﾋﾞｯﾌﾞｯﾍﾞｯﾎﾞ')
    expect(Nconv.romajiToHankakuKatakana('ppappippuppeppo')).toBe('ｯﾊﾟｯﾋﾟｯﾌﾟｯﾍﾟｯﾎﾟ')

    expect(Nconv.romajiToHankakuKatakana('kkyakkyikkyukkyekkyo')).toBe('ｯｷｬｯｷｨｯｷｭｯｷｪｯｷｮ')
    expect(Nconv.romajiToHankakuKatakana('ggyaggyiggyuggyeggyo')).toBe('ｯｷﾞｬｯｷﾞｨｯｷﾞｭｯｷﾞｪｯｷﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('ssyassyissyussyessyo')).toBe('ｯｼｬｯｼｨｯｼｭｯｼｪｯｼｮ')
    expect(Nconv.romajiToHankakuKatakana('zzyazzyizzyuzzyezzyo')).toBe('ｯｼﾞｬｯｼﾞｨｯｼﾞｭｯｼﾞｪｯｼﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('jjyajjyijjyujjyejjyo')).toBe('ｯｼﾞｬｯｼﾞｨｯｼﾞｭｯｼﾞｪｯｼﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('ttyattyittyuttyettyo')).toBe('ｯﾁｬｯﾁｨｯﾁｭｯﾁｪｯﾁｮ')
    expect(Nconv.romajiToHankakuKatakana('ccyaccyiccyuccyeccyo')).toBe('ｯﾁｬｯﾁｨｯﾁｭｯﾁｪｯﾁｮ')
    expect(Nconv.romajiToHankakuKatakana('ddyaddyiddyuddyeddyo')).toBe('ｯﾁﾞｬｯﾁﾞｨｯﾁﾞｭｯﾁﾞｪｯﾁﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('hhyahhyihhyuhhyehhyo')).toBe('ｯﾋｬｯﾋｨｯﾋｭｯﾋｪｯﾋｮ')
    expect(Nconv.romajiToHankakuKatakana('bbyabbyibbyubbyebbyo')).toBe('ｯﾋﾞｬｯﾋﾞｨｯﾋﾞｭｯﾋﾞｪｯﾋﾞｮ')

    expect(Nconv.romajiToHankakuKatakana('ffaffiffuffeffo')).toBe('ｯﾌｧｯﾌｨｯﾌｯﾌｪｯﾌｫ')
    expect(Nconv.romajiToHankakuKatakana('jjajjijjujjejjo')).toBe('ｯｼﾞｬｯｼﾞｯｼﾞｭｯｼﾞｪｯｼﾞｮ')
    expect(Nconv.romajiToHankakuKatakana('qqaqqiqquqqeqqo')).toBe('ｯｸｧｯｸｨｯｸｯｸｪｯｸｫ')
    expect(Nconv.romajiToHankakuKatakana('vvavvivvuvvevvo')).toBe('ｯｳﾞｧｯｳﾞｨｯｳﾞｯｳﾞｪｯｳﾞｫ')

    expect(Nconv.romajiToHankakuKatakana('sshi')).toBe('ｯｼ')
    expect(Nconv.romajiToHankakuKatakana('cchi')).toBe('ｯﾁ')
    expect(Nconv.romajiToHankakuKatakana('ttsu')).toBe('ｯﾂ')

    expect(Nconv.romajiToHankakuKatakana('xxaxxixxuxxexxo')).toBe('ｯｧｯｨｯｩｯｪｯｫ')
    expect(Nconv.romajiToHankakuKatakana('llallillullello')).toBe('ｯｧｯｨｯｩｯｪｯｫ')
    expect(Nconv.romajiToHankakuKatakana('xxyaxxyuxxyo')).toBe('ｯｬｯｭｯｮ')
    expect(Nconv.romajiToHankakuKatakana('llyallyullyo')).toBe('ｯｬｯｭｯｮ')
    expect(Nconv.romajiToHankakuKatakana('xxtu')).toBe('ｯｯ')
    expect(Nconv.romajiToHankakuKatakana('lltu')).toBe('ｯｯ')
    expect(Nconv.romajiToHankakuKatakana('xxtsu')).toBe('ｯｯ')
    expect(Nconv.romajiToHankakuKatakana('lltsu')).toBe('ｯｯ')

    expect(Nconv.romajiToHankakuKatakana('kkkkka')).toBe('ｯｯｯｯｶ')
  })

})
